CREATE TABLE IF NOT EXISTS CUSTOMER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ADDRESS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CEP VARCHAR(10) NOT NULL,
    LOGRADOURO VARCHAR(255),
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255),
    LOCALIDADE VARCHAR(255),
    UF VARCHAR(2),
    CUSTOMER_ID BIGINT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);